export const CONSTANTS = {
    // DB CONSTANTS
    DB_NAME: "NodeTraining",
    DB_USERNAME: "postgres",
    DB_PASSWORD: "$Sri@Krishna_143$",
    DB_PORT: "5432",
    DB_HOST: "localhost",
    DB_TYPE: "postgres",

    // JWT_SALT_KEY
    JWT_SALT: "eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4OTgzMjA5MywiaWF0IjoxNjg5ODMyMDkzfQ.kdcgDyWEILsvLECYOBJUaCy41XxzDBtuNC5VeP4E4ljtonGK5-qZ7YYITYhoLWP64wwBdCCyIgnNuwufYC_yKg",
    CRYPTO_SALT: "eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4OTg0MTE0MCwiaWF0IjoxNjg5ODQxMTQwfQ.9_-HJCViWI7sOQCBCSA-FHKqo50l2JSdcx9WANO0C_E1E_dP-EaEBktf2wKbyLZDk4vU8Vj98kOnEx0sa-6lfg"
}